In [1]:
import numpy as np

In [10]:
b = np.zeros([4])
b

array([ 0.,  0.,  0.,  0.])

In [4]:
a = np.ones([3,4])
print(a.shape)
b = a.tolist()
print(b)
print(a[2][1])
print(sum(a))
print(sum(a[1][:]))
ac = a
a[1][1] = 5
print(ac)
print(ac.astype(int))

(3, 4)
[[1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0]]
1.0
[ 3.  3.  3.  3.]
4.0
[[ 1.  1.  1.  1.]
 [ 1.  5.  1.  1.]
 [ 1.  1.  1.  1.]]
[[1 1 1 1]
 [1 5 1 1]
 [1 1 1 1]]


In [5]:
print(a[0,:])

[ 1.  1.  1.  1.]


#1 delete

In [7]:
a = list(range(5))
b = np.delete(a,[0,1])
print(b)

[2 3 4]


In [9]:
print(a)

[0, 1, 2, 3, 4]


In [6]:
min(1,10)

1

In [9]:
c = [1,2,3]
print(sum(c))

6


numpy math operation

In [10]:
a = np.ones([1,5])
b = (a >= 0.5)
print(b)
print(sum(sum(b)))

[[ True  True  True  True  True]]
5


In [ ]:
#get random choice

In [4]:
ids = [2732, 3187, 3964, 6062, 12305, 7017, 10379, 4664, 8429, 4086]
print(np.random.choice(ids,size = 3))

[3187 8429 4664]


In [17]:
chosen_ids_is = np.random.randint(0,10,5)
chosen_ids_is
np.random.randint(10)

6

In [16]:
aa = 0
for i in range(100000):
    aa = aa + 1 + i
print(aa)

5000050000


In [14]:
print(np.random.randint(4))

2
