In [2]:
import numpy, scipy.io

data = {'1':2,'3':4,'5':6}
scipy.io.savemat('test.mat', data, oned_as='row')
#savemat('./arrdata1.mat', mdict={'arr': arr})


In [1]:
import scipy.io as io
import numpy as np

y1=np.array([1,2,3,4])
y2=np.array([10,20,30,40])
y3=np.array([100,200,300,400])

a={}
a['test1']=y1
a['test2']=y2
a['test3']=y3
io.savemat('temp',a)
b = io.loadmat('temp')

print(b['test1'])
print(b['test2'])
print(b['test3'])

[[1 2 3 4]]
[[10 20 30 40]]
[[100 200 300 400]]


#save as string list

In [6]:
str_list = ['aa','bb','cc']
io.savemat('temp1',mdict={'temp1':str_list})
