In [2]:
import numpy as np
outfile = './test_file.npy'
a = np.ones([3,3])
np.save(outfile,a)

In [3]:
b = np.load(outfile)
print(b)

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


###To save multiple array###
use dictionary

(2) Save mat

In [4]:
import numpy, scipy.io

arr = numpy.arange(9)
arr = arr.reshape((3, 3))  # 2d array of 3x3
b = [[1,2,3],[4,5,6]]
scipy.io.savemat('./b.mat', mdict={'b': b})